from .bot1__main_manhattan import time_lapse_fn_bot_1
from .bot2_main_manhattan import time_lapse_fn_bot2
from .bot3_main_manhattan import time_lapse_fn_bot3
from .bot4_MCTS import time_lapse_fn_bot4
from .bot4_new_attempt import time_lapse_fn_bot4_new
from .bot4_probability import time_lapse_fn_bot4_prob